name: Percy Visual Test

on:
  workflow_dispatch:  # Enables the "Run Workflow" button in GitHub Actions

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Percy CLI
        run: npm install -g @percy/cli

      - name: Run Percy Test
        run: percy snapshot https://rencee.com
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
