name: Percy Visual Test

on:
  workflow_dispatch:  # Enables manual run via "Run Workflow" button

jobs:
  visual-regression:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install --save-dev @percy/cli puppeteer

      - name: Debug Percy Installation
        run: npx percy --version

      - name: Fix Percy Permissions
        run: chmod +x ./node_modules/.bin/percy

      - name: Create Puppeteer Test Script
        run: |
          echo "const puppeteer = require('puppeteer');
          const percySnapshot = require('@percy/puppeteer');

          (async () => {
            const browser = await puppeteer.launch();
            const page = await browser.newPage();
            await page.goto('https://rencee.com');
            await percySnapshot(page, 'Homepage');
            await browser.close();
          })();" > test.js

      - name: Run Percy with Puppeteer
        run: npx percy exec -- node test.js
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
